#define the images to be used for the characters here. 
#image deannaSleep = "deanna_sleep.png"
image bg_stb1_page1 = "images/Storybook 1/bg stb1_page 1.png"
image bg_stb1_page2 = "images/Storybook 1/bg stb1_page 2.png"
image bg_stb1_page3_1 = "images/Storybook 1/bg stb1_page 3_1.png"
image bg_stb1_page3_2 = "images/Storybook 1/bg stb1_page 3_2.png"
image bg_stb1_page4 = "images/Storybook 1/bg stb1_page 4.png"
image bg_stb1_page5 = "images/Storybook 1/bg stb1_page 5.png"
image stb1_deanna_worried = "images/Storybook 1/deanna_close_worried.png"
image stb1_EXTRA = "images/Storybook 1/EXTRA.png"
image stb1_deanna_call_out = "images/Storybook 1/stb1_page 3_deanna calling out.png"
image stb1_deanna_wake_up = "images/Storybook 1/stb1_page 3_deanna waking up 1.png"
image stb1_deanna_wake_up_2 = "images/Storybook 1/stb1_page 3_deanna waking up 2.png"
image stb1_deanna_kneel_wake_up = "images/Storybook 1/stb1_page 3_deanna waking up 3.png"
image stb1_scarry_sound_sfx1 = "images/Storybook 1/stb1_page4_sfx 1.png"
image stb1_scarry_sound_sfx2 = "images/Storybook 1/stb1_page4_sfx 2.png"