"""
definitions of images to be used in storybook 2,
all images should start with stb2_, unless they are a background image
those images will start with a bg_stb2_"""

image bg_stb2_page1 = "images/Storybook 2/bg stb2_page 1.png"
image bg_stb2_page2 = "images/Storybook 2/bg stb2_page 2.png"
image bg_stb2_page3 = "images/Storybook 2/bg stb2_page 3.png"
image bg_stb2_page4 = "images/Storybook 2/bg stb2_page 4.png"
image bg_stb2_page5 = "images/Storybook 2/bg stb2_page 4.png"
image bg_stb2_page5 = "images/Storybook 2/bg stb2_page 5.png"
image bg_stb2_page6 = "images/Storybook 2/bg stb2_page 6.png"
image bg_stb2_page7 = "images/Storybook 2/bg stb2_page 7.png" 
image bg_stb2_page8 = "images/Storybook 2/bg stb2_page 8.png"
image bg_stb2_page9 = "images/Storybook 2/bg stb2_page 9.png"
image bg_stb2_page10 = "images/Storybook 2/bg stb2_page 10.png"
image bg_stb2_page11 = "images/Storybook 2/bg stb2_page 11.png"
image bg_stb2_page12 = "images/Storybook 2/bg stb2_page 12.png"
image stb2_d_angry_closeup = "images/Storybook 2/deanna_close_angry.png"
image stb2_d_curious_closeup = "images/Storybook 2/deanna_close_curious.png"
image stb2_d_happy_closeup = "images/Storybook 2/deanna_close_happy.png"
image stb2_letho_laugh_closeup = "images/Storybook 2/lethabo_close_laughing.png"
image stb2_d_screaming = "images/Storybook 2/lethabo_close_laughing.png"
image stb2_page4_scarry_figure1 = "images/Storybook 2/stb2_page 4_scary figure 1.png"
image stb2_page4_scarry_figure2 = "images/Storybook 2/stb2_page 4_scary figure 2.png"
image stb2_athos_hanging = "images/Storybook 2/stb2_page 5_athos hanging 1.png"
image stb2_athos_swinging1 = "images/Storybook 2/stb2_page 5_athos hanging 2.png"
image stb2_athos_swinging2 = "images/Storybook 2/stb2_page 5_athos hanging 3.png"
image stb2_athos_falling_tree1 = "images/Storybook 2/stb2_page 5_athos hanging 4.png"
image stb2_athos_falling_tree2 = "images/Storybook 2/stb2_page 5_athos hanging 5.png"
image stb2_ballon_page5 = "images/Storybook 2/stb2_page 5_balloon.png"
image stb2_letho_climb_tree1 = "images/Storybook 2/stb2_page 5_lethabo on tree 1.png"
image stb2_letho_climb_tree2 = "images/Storybook 2/stb2_page 5_lethabo on tree 2.png"
image stb2_letho_claw_swipe_tree1 = "images/Storybook 2/stb2_page 5_lethabo on tree 3.png"
image stb2_letho_claw_swipe_tree2 = "images/Storybook 2/stb2_page 5_lethabo on tree 4.png"
image stb2_claw_slash_page5 = "images/Storybook 2/stb2_page 5_slash 1.png"
image stb2_claw_slash_page5_2 = "images/Storybook 2/stb2_page 5_slash 2.png"
image stb2_d_look_1_page6 = "images/Storybook 2/stb2_page 6_deanna look 1.png"
image stb2_d_look_2_page6 = "images/Storybook 2/stb2_page 6_deanna look 2.png"
image stb2_d_look_3_page6 = "images/Storybook 2/stb2_page 7_deanna look 3.png"
image stb2_page8_athos_floor1 = "images/Storybook 2/stb2_page 8_athos on floor 1.png"
image stb2_page8_athos_floor2 = "images/Storybook 2/stb2_page 8_athos on floor 2.png"
image stb2_page8_athos_floor3 = "images/Storybook 2/stb2_page 8_athos on floor 3.png"
image stb2_page8_athos_floor4 = "images/Storybook 2/stb2_page 8_athos on floor 4.png"
image stb2_page8_d_1 = "images/Storybook 2/stb2_page 8_deanna 1.png"
image stb2_page8_d_2 = "images/Storybook 2/stb2_page 8_deanna 2.png"
image stb2_page8_d_3 = "images/Storybook 2/stb2_page 8_deanna 3.png"
image stb2_page9_aesop_vfx1 = "images/Storybook 2/stb2_page 9_aesop vfx 1.png"
image stb2_page9_aesop_vfx2 = "images/Storybook 2/stb2_page 9_aesop vfx 2.png"
image stb2_page9_d_1 = "images/Storybook 2/stb2_page 9_deanna 1.png"
image stb2_page9_d_2 = "images/Storybook 2/stb2_page 9_deanna 2.png"
image stb2_page10_atho_letho1 = "images/Storybook 2/stb2_page 10_athos and lethabo 1.png"
image stb2_page10_atho_letho2 = "images/Storybook 2/stb2_page 10_athos and lethabo 2.png"
image stb2_page10_d_1 = "images/Storybook 2/stb2_page 10_deanna 1.png"
image stb2_page10_d_2 = "images/Storybook 2/stb2_page 10_deanna 2.png"
image stb2_page11_athos_letho = "images/Storybook 2/stb2_page 11_athos and lethabo.png"
image stb2_page11_d = "images/Storybook 2/stb2_page 11_deanna.png"